Update Implementation for Date Creation in DG
AY2122S2-CS2103T-T17-3/tp pull request #179
Opened 2022-04-06 09:00 UTC by pyk595

The Developer Guide does not have documentation for date creation
processes. This may make the design confusing for reviewers.

Let's do the following to close AY2122S2-CS2103T-T17-3#174:
- Update implementation for date creation
- Add design consideration
- Update glossary

2022-04-06 14:54 UTC, ngjunkang requested changes
Some changes to be made

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +In the event that data saved in the saved json file is corrupted, the `Storage component` will make a copy of the
1. "corrupted or can't be read".
2. `Storage` component

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +Users will still be able to use all features available, but the existing `addressbook.json` will be overwritten.
"overwritten with the default contact list"

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +As seen in the [`Model` component](#model-component), Each `Person` object contains its own `BirthDate` object,
"each"

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +a `ContactedInfoList` and a `ReminderList`. The `ContactedInfoList` stores `ContactedInfo` objects,
list of `ContactedInfo`? since there's no class, `ContactedInfoList`

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +* A `DocumentedDate` object has a private `LocalDate` member to allow the application to easily display a formatted date.
"to easily display a formatted date" -> "to store a date"?

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +
extra line break?

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +The method will process the `validDate` into a `String` called `trimmedDate` and call
"process" -> "trim"

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> + `DocumentedDate#isValidDate(trimmedDate)` to check if it is a valid date. if the `trimmedDate` is indeed a valid date,
"it is in a valid date format"

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +    * Less bug prone as each child class is independent of each other.
is the bullet intentional? check for other bullets in `Design Consideration` as well.

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +    * Pros: We can use polymorphism to modify certain behaviour of each specific child class (i.e. Allowing `BirthDate`
I think this is not polymorphism, which is like you are using `DocumentedDate` as the object instead. and you say the object takes many forms, like ReminderDate...

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +      Liskov Substitution Principle in mind.
LSP: you might get bashed. `isToday()` in `BirthDate` violates LSP.

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +
unnecessary line break?

2022-04-06 14:54 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +* Alternative 2: Use `DocumentedDate`, but use other components to differentiate (i.e. `enum` types)
elaborate on this? I don't really understand. Use `DocumentedDate` as the actual date?

2022-04-06 15:18 UTC, ngjunkang commented on docs/DeveloperGuide.md
> +
nice

2022-04-06 17:03 UTC, cashewnade commented on docs/DeveloperGuide.md
> +able to be created using a date in the future. The rationale is because `RecentDate` keep track of the user's
`RecentDate` keeps track of...

2022-04-06 17:07 UTC, cashewnade commented on docs/DeveloperGuide.md
> +Having two levels of checks ensure that when the working "date" type objects are less bug prone due when using the specific
"Having two levels of checks ensures that working "date" type objects are less bug prone, when using specific "date" type objects for their designated usages."

2022-04-07 09:42 UTC, ngjunkang approved these changes
Looks good..

2022-04-07 10:33 UTC, merged