Update DG for reminders feature
AY2122S2-CS2103T-T17-3/tp pull request #215
Opened 2022-04-08 22:07 UTC by cashewnade

this will close https://github.com/AY2122S2-CS2103T-T17-3#214

2022-04-09 04:12 UTC, pyk595 approved these changes
LGTM

2022-04-09 06:10 UTC, ngjunkang requested changes
Hi, many of the activation bar does not end at the right place, for example, ParserUtil in AddReminderCommandSequenceDiagram. The activation bar should be separated. one for description and other for date.

2022-04-10 01:09 UTC, pyk595 requested changes
Some things to fix

2022-04-10 01:09 UTC, pyk595 commented on docs/diagrams/DeleteReminderFromReminderListSeqDiagram.puml
> +PriorityQueueCopy --> ReminderListCopy : reminderPriorityQueueCopy
Move line 39 and 40 to line 56

2022-04-10 01:09 UTC, pyk595 commented on docs/diagrams/DeleteReminderFromReminderListSeqDiagram.puml
> +ReminderList -> PriorityQueueCopy : reminderPriorityQueue.remove(reminder)
`ReminderListCopy->PriorityQueueCopy: remove(reminder)`

2022-04-10 01:09 UTC, pyk595 commented on docs/diagrams/DeleteReminderFromReminderListSeqDiagram.puml
> +PriorityQueueCopy --> ReminderList : reminderPriorityQueueCopy
`PriorityQueueCopy-->ReminderListCopy`...the other stuff

2022-04-10 01:09 UTC, pyk595 commented on docs/diagrams/DeleteReminderFromReminderListSeqDiagram.puml
> +PriorityQueueCopy -> PriorityQueueCopy : remove(reminder)
line 48 to 50 can delete

2022-04-10 01:09 UTC, pyk595 commented on docs/diagrams/AddReminderCommandParserSeqDiagram.puml
> +Reminder --> AddReminderCommandParser : Reminder
`Reminder --> AddReminderCommandParser: toAdd`

2022-04-10 01:09 UTC, pyk595 commented on docs/diagrams/AddReminderCommandParserSeqDiagram.puml
> +ReminderDescription --> ParserUtil : ReminderDescription
`ReminderDescription --> ParserUtil: reminderDescription`

2022-04-10 07:21 UTC, pyk595 requested changes

2022-04-10 07:21 UTC, pyk595 commented on docs/diagrams/AddReminderCommandParserSeqDiagram.puml
> +ReminderDescription --> ParserUtil: reminderDescription
II gave you some comments in telegram, you can refer to those and make some small edits, thanks!

2022-04-10 09:52 UTC, pyk595 approved these changes
LGTM

2022-04-10 10:27 UTC, ngjunkang approved these changes

2022-04-10 10:43 UTC, merged