Add custom date model
AY2122S2-CS2103T-T17-3/tp pull request #30
Opened 2022-03-04 13:43 UTC by pyk595

The application does not have a date class to handle time based
events easily.

Let's make a custom date class to close #29 
so future increments like adding a birthdate, adding a
reminder and adding previous contacted date can manipulate
time based events.

2022-03-04 15:20 UTC, ngjunkang requested changes
It looks like you are improving `LocalDate` by adding two methods, `getDaysPassed` and `isToday`. I don't have any preference whether we should add this class, depends on how you want to use it. Just some comments you can improve on.

2022-03-05 06:25 UTC, pyk595 commented on src/test/java/seedu/address/model/date/DateTest.java
> +        int days = (int) DAYS.between(testDate, today);
This shouldn't be an issue because the number of days required to hit integer overflow would exceed the user's usage capacity for this software

2022-03-05 06:30 UTC, ngjunkang commented on src/test/java/seedu/address/model/date/DateTest.java
> +        int days = (int) DAYS.between(testDate, today);
How about getDaysPassed's implementation?

2022-03-05 12:59 UTC, ngjunkang approved these changes
Fixed all commented code. LGTM!

2022-03-05 12:59 UTC, merged